### ISSUE TITLE
Holding A will not viewlock while repairing barricades

### ISSUE THREAD

**Issue by MotoLegacy** [tyleryoung88/quakegx-nzp#57]
Check CoD to see if this is actually how it should be

**Comment by seniormeatbox** [comment]
This is how it is on bo1 and bo2 wii unfortunately but It would be a good QOL thing to have it work like this

**Comment by MotoLegacy** [comment]
> This is how it is on bo1 and bo2 wii unfortunately but It would be a good QOL thing to have it work like this

let's let sB independently verify the feature being like this and evaluate whether its a necessary change. i could see this going both ways, being able to turn around while repairing seems valuable. its best not to be too opinionated when doing these passes

**Comment by sbeeds** [comment]
Verified that viewlock does not lock the screen while repairing barricades on black ops 1 wii. This is the preferred functionality in my opinion.
