### ISSUE TITLE
"Restart" isn't properly resetting everything in the map

### ISSUE THREAD

**Issue by seniormeatbox** [tyleryoung88/quakegx-nzp#63]
Hitting "Restart"" in the pause menu resets doors and barriers but enemies are still spawning in rooms opened before the restart that are not opened. In Nacht, explosive barrels detonated before the restart do not respawn

**Comment by MotoLegacy** [comment]
this is an NZP gamecode issue. this should be closed and anything new you find should be added to the main nzp issue for this.
